spring.application.name=mongo
server.port=8080

# MongoDB
spring.mongodb.uri=mongodb://localhost:3000
spring.mongodb.database=customerdb
spring.mongodb.username=admin
spring.mongodb.password=approot123
spring.data.mongodb.auto-index-creation=true



# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.example=DEBUG
