spring.application.name=mongo
server.port=8080

# MongoDB
spring.mongodb.uri=mongodb://localhost:3000
spring.mongodb.database=customerdb
spring.mongodb.username=admin
spring.mongodb.password=approot123
spring.data.mongodb.auto-index-creation=true

# Keycloak / OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://lcoalhost:8000/realms/test
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://lcoalhost:8000/realms/test/protocol/openid-connect/certs

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.example=DEBUG
